# Generated by Django 4.0 on 2024-08-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/meals/'),
        ),
    ]
